# Generated by Django 5.2.9 on 2026-01-06 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('message', models.CharField(max_length=120)),
                ('done_at', models.DateTimeField(auto_now_add=True)),
                ('from_acc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_transactions', to='accounts.account')),
                ('to_acc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_transactions', to='accounts.account')),
            ],
        ),
    ]
